Repository what-is-your-ideal-type/FE_what-is-your-ideal-type, pull requests merged in 2024-09, with the labels that each got.

#100 Feat: 구글 로그인 구현, 이미지 관련 프로필 생성 로직 추가 Refactor: 로그인 관련 로직 분리
  src/pages/Generate.tsx
  src/pages/Home.tsx
  src/pages/MyPage.tsx
  src/pages/Result.tsx
  src/services/auth/loginWithEmail.ts
  src/services/auth/loginWithGoogle.ts
  src/services/auth/logoutService.ts
  src/services/profileGenerator.ts
  src/services/uploadImageToFirebase.ts
Labels: ✨ Feature, 🔨 Refactor

#101 Deploy : 3차 main merge
  .github/ISSUE_TEMPLATE/✅-feat--추가-기능.md
  .github/ISSUE_TEMPLATE/🐞--bug--버그-리포트.md
  .github/ISSUE_TEMPLATE/📝-test--테스트.md
  .github/ISSUE_TEMPLATE/🔨-refactor--리팩토링.md
  .github/PULL_REQUEST_TEMPLATE.md
  package-lock.json
  package.json
  src/components/Button.tsx
  src/components/Loading.tsx
  src/components/Picture.tsx
  src/components/PreventDefaultWrapper.tsx
  src/components/Survey.ts
  src/pages/Generate.tsx
  src/pages/Home.tsx
  src/pages/MyPage.tsx
  src/pages/Result.tsx
  src/pages/Survey.tsx
  src/services/auth/loginWithEmail.ts
  src/services/auth/loginWithGoogle.ts
  src/services/auth/logoutService.ts
  src/services/imageGenerator.ts
  src/services/profileGenerator.ts
  src/services/saveResultUrlToFirebase.ts
  src/services/uploadImageToFirebase.ts
  vercel.json
Labels: 🌏 Deploy

#104 refactor: 컴포넌트 수정
  src/components/Button.tsx
  src/components/Input.tsx
  src/components/Text.ts
  src/pages/Home.tsx
  src/pages/Survey.tsx
  src/reset.css
Labels: 🔨 Refactor

#108 fix: 응답 prompts JSON으로 변경
  src/pages/Result.tsx
  src/services/profileGenerator.ts
Labels: 🐞 BugFix

#110 Fix: craco 설정, 외부 모듈 import 에러 해결
  craco.config.js
  package-lock.json
  package.json
Labels: 🐞 BugFix

#111 Refactor: generate, result 페이지에서 뒤로가기 방지 기능 추가
  src/pages/Generate.tsx
  src/pages/Result.tsx
Labels: ✨ Feature, 🔨 Refactor

#114 fix: 프롬프트 버그 수정
  src/pages/Generate.tsx
  src/pages/Survey.tsx
  src/services/imageGenerator.ts
  src/services/profileGenerator.ts
Labels: 🐞 BugFix

#116 refactor: 설문 조정
  src/components/utils/Survey.ts
Labels: 🔨 Refactor

#118 Feat: Survey 문항 트랜지션 추가 / Fix: Generate UI 색상 변경
  public/images/spin.gif
  src/components/ui/Loading.tsx
  src/pages/Survey.tsx
Labels: 🎨 Html&css, ✨ Feature

#120 Refactor: Generate progress 업데이트 로직 단계별 정확도 반영, 점진적 퍼포먼스 개선
  src/App.tsx
  src/components/ui/Loading.tsx
  src/pages/Generate.tsx
Labels: 🔨 Refactor

#122 Feat: header 로그인여부 판별로직, 로그아웃 추가 / Fix: 페이지 header 추가
  src/components/ui/Header.tsx
  src/pages/MyPage.tsx
  src/pages/Result.tsx
Labels: ✨ Feature

#123 feat: 정렬 드롭다운 생성, refactor: 이미지 최신 순 저장
  src/components/ui/Dropdown.tsx
  src/pages/Generate.tsx
  src/pages/MyPage.tsx
Labels: ✨ Feature, 🔨 Refactor
