Repository what-is-your-ideal-type/FE_what-is-your-ideal-type, pull requests merged in 2024-08, with the labels that each got.

#92 Fix: Result 페이지 로그인여부 판별 로직 수정
  src/pages/Result.tsx
Labels: 🐞 BugFix

#94 Feat: 마이페이지에 결과페이지 url 추가, Update: 바로 다운로드 기능 모바일에도 가능하게 수정
  src/components/Picture.tsx
  src/components/PreventDefaultWrapper.tsx
  src/pages/Generate.tsx
  src/pages/MyPage.tsx
  src/pages/Result.tsx
  src/services/saveResultUrlToFirebase.ts
  src/services/uploadImageToFirebase.ts
Labels: ✨ Feature

#95 test: 아이폰 테스트
  src/components/Button.tsx
  src/components/Survey.ts
  src/pages/MyPage.tsx
  src/services/imageGenerator.ts
Labels: ✅ Test

#97 refactor: AI 요청 프롬프트 수정
  src/components/Button.tsx
  src/components/Survey.ts
  src/pages/MyPage.tsx
  src/services/imageGenerator.ts
Labels: 🔨 Refactor

#99 Feat: Survey 페이지 문항 넘어갈 때 스와이프 애니메이션 구현
  package-lock.json
  package.json
  src/pages/Survey.tsx
Labels: ✨ Feature
