Repository what-is-your-ideal-type/FE_what-is-your-ideal-type, pull requests merged in 2024-07, with the labels that each got.

#29 Feat: firebase 연동 및 회원가입 validation 추가
  package-lock.json
  package.json
  src/App.tsx
  src/Pages/Home.tsx
  src/Pages/SignUp.tsx
  src/firebase.ts
Labels: ✨ Feature

#39 Update: yml 추가: screts Actions로 자동 업데이트
  .github/workflows/main.yml
  src/App.tsx
Labels: ⚙ Setting

#40 Fix: 스타일 타입 지정 및 확장 / Feat: Home => Survey 라우터 설정 및 타입 추가
  src/Pages/Home.tsx
  src/components/Button.tsx
  src/components/ButtonArgs.ts
Labels: 🐞 BugFix

#41 Feat: survey => result ai 요청 결과 불러오기 / Fix: Loading.tsx 컴포넌트 함수 표현식으로 변경
  src/Pages/Result.tsx
  src/Pages/Survey.tsx
  src/components/Loading.tsx
  src/index.tsx
  src/services/imageGenerator.tsx
Labels: ✨ Feature

#42 Feat: 생성 이미지 storage 업로드
  src/Pages/Result.tsx
  src/firebase.ts
  src/services/uploadImage.ts
Labels: ✨ Feature

#43 Update: Survey 문항 변경, image생성 요청 문구 변경
  src/Pages/Survey.tsx
  src/components/Survey.ts
  src/services/imageGenerator.tsx
Labels: 🔨 Refactor

#45 Update: '섹시한'키워드 삭제 / '숏컷' => '여자 숏컷' 변경 / '힙합 스타일' 중복으로 제거 / 생성결과 프롬프트 반환, 설문 항목 변경
  src/Pages/Result.tsx
  src/Pages/Survey.tsx
  src/components/Survey.ts
  src/services/imageGenerator.tsx
Labels: 🔨 Refactor

#49 Fix: CORS오류 proxy로 해결
  package.json
  src/services/uploadImage.ts
Labels: 🐞 BugFix

#52 Docs: Issues_Template 추가
  .github/ISSUE_TEMPLATE/📝-test--테스트.md
  .github/ISSUE_TEMPLATE/🔨-refactor--리팩토링.md
Labels: 📃 Docs

#55 Refactor: useLocation => useParams로 데이터 전달 방식 변경
  src/App.tsx
  src/Pages/Result.tsx
  src/Pages/Survey.tsx
  src/services/imageGenerator.tsx
Labels: 🔨 Refactor

#59 Fix: React props Warning 제거
  src/components/Button.tsx
  src/components/ButtonArgs.ts
Labels: 🐞 BugFix

#60 Update: 이미지 저장(로그인, 비로그인 구분해서 저장) / Feat: myPage에서 해당 유저의 firebase 이미지 보여주기
  src/Pages/MyPage.tsx
  src/Pages/Result.tsx
  src/firebase.ts
  src/services/uploadImage.ts
Labels: ✨ Feature

#61 Feat: Loading 컴포넌트 추가, Result 링크 공유하기 로직 추가, 로그인 상태를 저장하는 AuthContext 로직 추가
  src/App.tsx
  src/Pages/Home.tsx
  src/Pages/MyPage.tsx
  src/Pages/Result.tsx
  src/Pages/Survey.tsx
  src/components/Loading.tsx
  src/components/Survey.ts
  src/contexts/AuthContext.tsx
Labels: 🐞 BugFix, ✨ Feature

#65 Feat: 이미지 파일명 랜덤 생성, 로그아웃 기능 추가, Refactor: 브라우저 탭 닫으면 인증 지속 종료
  package-lock.json
  package.json
  src/Pages/Home.tsx
  src/contexts/AuthContext.tsx
  src/services/uploadImage.ts
Labels: ✨ Feature, 🔨 Refactor

#66 Feat: WebP로 변환 후 업로드 및 다운로드
  src/App.tsx
  src/Pages/Generate.tsx
  src/Pages/Result.tsx
  src/Pages/Survey.tsx
  src/services/convertToWebP.ts
  src/services/imageGenerator.ts
  src/services/requestImage.ts
  src/services/uploadImageToFirebase.ts
Labels: ✨ Feature

#67 Update: requestImage 삭제, SEO Performance 점수 향상을 위한 img 속성 추가
  src/Pages/Generate.tsx
  src/Pages/Result.tsx
  src/services/requestImage.ts
Labels: 🔨 Refactor

#68 Update: 이미지 해상도 및 품질 다운그레이드
  src/services/convertToWebP.ts
Labels: 🔨 Refactor

#70 Update: 사용하지 않는 이미지, 테스트파일, 로직 삭제
  labels.json
  package-lock.json
  package.json
  public/images/ideal-image.png
  public/images/image 13.png
  src/App.test.tsx
  src/App.tsx
  src/Pages/Result.tsx
  src/pages.ts
  src/test/Survey.test.tsx
Labels: 🔨 Refactor

#72 Update: 코드 스플리팅: lazy, suspsnse / img 태그 Picture 컴포넌트로 확장
  src/App.tsx
  src/Pages/Generate.tsx
  src/Pages/Result.tsx
  src/Pages/Survey.tsx
  src/components/Loading.tsx
  src/components/Picture.tsx
Labels: 🔨 Refactor

#78 Update: 사진 저장 버튼 클릭시(새창열림->바로 다운로드), Feat: 결과 이미지 우클릭과 드래그 방지
  src/Pages/Generate.tsx
  src/Pages/Result.tsx
  src/components/Picture.tsx
  src/services/uploadImageToFirebase.ts
Labels: ✨ Feature

#79 Feat: 설문 중 뒤로가기 기능
  src/Pages/Survey.tsx
  src/components/Survey.ts
  src/firebase 2.ts
Labels: ✨ Feature

#80 Update: 요청 프롬프트 영어로 변경
  src/Pages/Generate.tsx
  src/Pages/Survey.tsx
  src/components/Survey.ts
  src/services/imageGenerator.ts
Labels: 🔨 Refactor

#81 Feat: 이미지 생성 횟수 제한, survey 페이지 이동 버튼 컴포넌트 추가
  src/Pages/Generate.tsx
  src/Pages/Home.tsx
  src/Pages/MyPage.tsx
  src/components/NavigateToSurvey.tsx
  src/services/countService.ts
Labels: ✨ Feature

#82 Feat: 해쉬태그 firebase에 저장 후 MyPage에서 보여주는 기능 추가 & Fix: 로그아웃 후 input값 남아있는 것 수정, getCountAndTimeLeft 인자값 변경
  src/Pages/Generate.tsx
  src/Pages/Home.tsx
  src/Pages/MyPage.tsx
  src/services/uploadImageToFirebase.ts
Labels: 🐞 BugFix, ✨ Feature

#91 Fix: 로그인에 따라 결과페이지 버튼 다르게 안보이는 이슈 수정, 로그인 시 mypage로 이동
  src/pages/Home.tsx
  src/pages/Result.tsx
Labels: 🐞 BugFix
