Repository what-is-your-ideal-type/FE_what-is-your-ideal-type, pull requests merged in 2024-10, with the labels that each got.

#128 refactor: Header 홈 버튼 빼기
  src/components/ui/Header.tsx
Labels: 🔨 Refactor

#130 Feat: tanstack query 라이브러리 추가
  .eslintrc.js
  package-lock.json
  package.json
  src/App.tsx
Labels: ⚙ Setting, ✨ Feature

#131 feat: 무한 스크롤 구현
  package-lock.json
  package.json
  src/pages/MyPage.tsx
Labels: ✨ Feature
