Repository what-is-your-ideal-type/FE_what-is-your-ideal-type, pull requests merged in 2025-02, with the labels that each got.

#161 refactor: 유효성검사 zod,react-hook-form 으로 리팩토링
  package-lock.json
  package.json
  src/components/functional/find-password-modal.tsx
  src/components/ui/error-message.tsx
  src/components/ui/input.tsx
  src/components/utils/validation.ts
  src/pages/home.tsx
  src/pages/signup.tsx
Labels: 🔨 Refactor

#163 Refactor: generate 로직 개편, result 로직 분기 개편 / Feat: 로그인 시 데이터 마이그레이션 로직 추가
  src/App.tsx
  src/components/ui/header.tsx
  src/components/utils/cookies.ts
  src/components/utils/post-migration.ts
  src/pages/generate.tsx
  src/pages/result.tsx
  src/services/auth/login-with-email.ts
  src/services/auth/login-with-google.ts
  src/services/auth/logout.ts
Labels: ✨ Feature, 🔨 Refactor

#166 Refactor: Cookie 관련 로직 util 함수로 통합 및 개선
  src/components/functional/landing-route.tsx
  src/components/ui/header.tsx
  src/components/utils/cookies.ts
  src/components/utils/post-migration.ts
  src/hooks/use-guest-mode.ts
  src/pages/home.tsx
  src/pages/result.tsx
Labels: 🐞 BugFix, 🔨 Refactor

#169 Fix: 쿠키 값이 없을 경우 mypage로 리다이렉트되는 현상 해결
  src/components/utils/cookies.ts
Labels: 🐞 BugFix

#176 Fix: postList undefined일 경우 문제 해결 및 구글 로그인 후 유저 정보 추가
  src/components/utils/cookies.ts
  src/pages/mypage.tsx
  src/services/auth/login-with-google.ts
Labels: 🐞 BugFix

#187 Fix: 마이페이지 조건부 훅 호출 에러 해결
  src/components/utils/post-migration.ts
  src/pages/mypage.tsx
  src/services/auth/login-with-google.ts
  src/services/auth/logout.ts
Labels: 🐞 BugFix
