Repository what-is-your-ideal-type/FE_what-is-your-ideal-type, pull requests merged in 2025-03, with the labels that each got.

#201 Refactor: 결과페이지 nickname 표시, useNickname 훅 정의
  package-lock 2.json
  src/hooks/use-nickname.ts
  src/pages/result.tsx
Labels: 🔨 Refactor

#202 fix: result 페이지 fetch 로직 수정
  package-lock.json
  package.json
  src/components/functional/navigate-to-survey.tsx
  src/pages/home.tsx
  src/pages/mypage.tsx
  src/pages/result.tsx
Labels: 🐞 BugFix

#203 Feat: 페이지 라우팅 시 스크롤 최상단 이동, footer 추가, 로고 라우팅
  src/App.tsx
  src/components/ui/footer.tsx
  src/components/ui/header.tsx
  src/pages/mypage.tsx
  src/services/scroll-to-top.tsx
Labels: 🐞 BugFix, ✨ Feature
