Repository what-is-your-ideal-type/FE_what-is-your-ideal-type, pull requests merged in 2025-01, with the labels that each got.

#136 Fix : 마이페이지, 결과페이지 UI 수정 / generation에서 currentUser 유무에 따른 선택적 firebase 문서 업데이트 로직 수정
  .github/workflows/main.yml
  .gitignore
  package-lock.json
  package.json
  src/components/functional/KakaoShare.tsx
  src/components/functional/convertToWebP.ts
  src/components/ui/Header.tsx
  src/components/ui/Text.ts
  src/components/utils/ColorMap.ts
  src/pages/Generate.tsx
  src/pages/MyPage.tsx
  src/pages/Result.tsx
  src/services/auth/loginWithGoogle.ts
  src/styles/styled.ts
  vercel.json
Labels: 🎨 Html&css, 🐞 BugFix

#138 refactor: cra => vite 마이그레이션
  .github/ISSUE_TEMPLATE/✅-feat--추가-기능.md
  .github/ISSUE_TEMPLATE/🐞--bug--버그-리포트.md
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  craco.config.js
  index.html
  package-lock.json
  package.json
  public/favicon.ico
  src/firebase.ts
  src/react-app-env.d.ts
  src/services/imageGenerator.ts
  src/services/profileGenerator.ts
  src/vite-env.d.ts
  vercel.json
  vite.config.ts
Labels: ⚙ Setting

#140 feat: husky
  .husky/_/.gitignore
  .husky/_/applypatch-msg
  .husky/_/commit-msg
  .husky/_/h
  .husky/_/husky.sh
  .husky/_/post-applypatch
  .husky/_/post-checkout
  .husky/_/post-commit
  .husky/_/post-merge
  .husky/_/post-rewrite
  .husky/_/pre-applypatch
  .husky/_/pre-auto-gc
  .husky/_/pre-commit
  .husky/_/pre-merge-commit
  .husky/_/pre-push
  .husky/_/pre-rebase
  .husky/_/prepare-commit-msg
  package.json
Labels: ⚙ Setting

#141 fix: husky, package.json 수정
  .husky/_/post-merge
  .husky/_/pre-push
  package-lock.json
  package.json
Labels: 🐞 BugFix

#143 Fix: vite proxy 설정
  .husky/_/post-merge
  .husky/_/pre-push
  src/components/functional/convert-to-webp.ts
  src/pages/Generate.tsx
  src/pages/Result.tsx
  src/pages/Survey.tsx
  vite.config.ts
Labels: 🐞 BugFix

#144 fix: husky settings
  .husky/_/post-commit
  .husky/_/post-merge
  .husky/_/pre-commit
  .husky/_/pre-push
  package.json
Labels: ⚙ Setting

#145 feat: Error Boundary
  .husky/_/post-commit
  .husky/_/pre-commit
  .prettierrc
  package.json
  src/App.tsx
  src/components/functional/error-boudary.tsx
  src/components/functional/navigate-to-survey-props.tsx
  src/hooks/use-guest-mode.ts
  src/pages/Generate.tsx
  src/pages/Home.tsx
  src/pages/Result.tsx
  src/pages/Survey.tsx
  vite.config.ts
Labels: ✨ Feature

#147 feat: useGuestMode
  src/components/functional/navigate-to-survey-props.tsx
  src/hooks/use-guest-mode.ts
  src/pages/Generate.tsx
  src/pages/Home.tsx
Labels: ✨ Feature, 🔨 Refactor

#152 Refactor: generate 로딩 UI 개선
  package-lock.json
  package.json
  src/components/ui/header.tsx
  src/components/ui/loading-screen.tsx
  src/pages/generate.tsx
  src/pages/result.tsx
Labels: 🎨 Html&css, 🔨 Refactor

#153 review: tailwind 마이그레이션 코드 리뷰
  src/components/ui/button/button-group.tsx
  src/components/ui/button/button.tsx
  src/components/ui/flexbox.tsx
  src/components/ui/header.tsx
  src/components/ui/main.tsx
  src/components/ui/text.tsx
  src/pages/home.tsx
Labels: 🔨 Refactor

#155 fix: package.json 미사용 패키지 삭제
  package.json
  src/App.tsx
  src/components/ui/loading.tsx
  src/index.tsx
  src/report-web-vitals.ts
Labels: ⚙ Setting

#158 fix: invalid login or password 예외처리
  .github/workflows/sync-fork.yml
  src/services/auth/login-with-email.ts
Labels: 🐞 BugFix

#160 refactor: guestMode, localStorage => cookie로 변경
  .github/workflows/autoSync.yml
  package-lock.json
  package.json
  src/components/functional/landing-route.tsx
  src/components/functional/navigate-to-survey-props.tsx
  src/hooks/use-guest-mode.ts
  src/pages/home.tsx
Labels: 🔨 Refactor
